"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Language = void 0;
var Language;
(function (Language) {
    Language["Kh\u00F4ng"] = "Kh\u00F4ng";
    Language["Anh"] = "Anh";
    Language["Trung"] = "Trung";
    Language["Hindi"] = "Hindi";
    Language["T\u00E2y_Ban_Nha"] = "T\u00E2y Ban Nha";
    Language["Ph\u00E1p"] = "Ph\u00E1p";
    Language["\u1EA2_R\u1EADp"] = "\u1EA2 R\u1EADp";
    Language["Bengal"] = "Bengal";
    Language["Nga"] = "Nga";
    Language["B\u1ED3_\u0110\u00E0o_Nha"] = "B\u1ED3 \u0110\u00E0o Nha";
    Language["Indonesia"] = "Indonesia";
    Language["Urdu"] = "Urdu";
    Language["\u0110\u1EE9c"] = "\u0110\u1EE9c";
    Language["Nh\u1EADt"] = "Nh\u1EADt";
    Language["Swahili"] = "Swahili";
    Language["Marathi"] = "Marathi";
    Language["Telugu"] = "Telugu";
    Language["Th\u1ED5_Nh\u0129_K\u00EC"] = "Th\u1ED5 Nh\u0129 K\u00EC";
    Language["Tamil"] = "Tamil";
    Language["Punjab"] = "Punjab";
    Language["H\u00E0n"] = "H\u00E0n";
    Language["Vi\u1EC7t"] = "Vi\u1EC7t";
    Language["Hausa"] = "Hausa";
    Language["Java"] = "Java";
    Language["Italia"] = "Italia";
    Language["Gujarat"] = "Gujarat";
    Language["Th\u00E1i"] = "Th\u00E1i";
    Language["Amhara"] = "Amhara";
})(Language = exports.Language || (exports.Language = {}));
